### ISSUE TITLE
Relation with others work

### ISSUE THREAD

**Issue by bam80** [stellartux/plugin.video.lbry#4]
Hi, thanks for this.
Have you tried to team up or cooperate by any other means with other similar projects?
Accidentally found this: https://github.com/accumulator/plugin.video.lbry

**Comment by stellartux** [comment]
I haven't tried teaming up with anyone, I didn't know there were similar projects, I did most of the work for this project three years ago and it's been a while since I've done anything with this project, that one has only been up on Github for three days. I'm happy to accept pull requests or suggestions from anyone. I don't know why they decided to make their own version, I assume they have a reason they didn't want to use this one.

**Comment by mintsoft** [comment]
My money would be on that they checked the main repo, it wasn't there and assumed that they needed to make their own

**Comment by stellartux** [comment]
I'd been meaning to try to get this one in the official plug-in list. I'd planned at one point to have this plug-in automatically download the Lbry daemon, which would have made it ineligible because official plug-ins aren't allowed to download external binaries, but I never got round to doing it, and I'm starting think it might be better being easier to find on the official list than being slightly more convenient to use, especially for a feature that I probably won't actually get round to implementing.
